const tags = {
  general: [
    "Georgia",
    "Travel Georgia",
    "Visit Georgia",
    "Georgia Country",
    "Republic of Georgia",
    "South Caucasus",
    "Eurasia",
    "About Georgia",
    "Tbilisi",
    "Kutaisi",
    "Batumi",
    "Mtskheta",
    "Svaneti",
    "Kakheti",
    "Kazbegi",
    "Georgian Culture",
    "Georgian History",
    "Black Sea Coast",
    "Caucasus Mountains",
    "Georgian Language",
    "Georgian Lari (GEL)",
    "Travel Tips Georgia",
    "Georgia Tourism",
    "Holidays in Georgia",
    "Caucasus Travel",
    "Hospitality",
    "Safety in Georgia",
    "Budget Travel Georgia",
    "Luxury Travel Georgia",
    "Getting Around Georgia"
  ],
  history: [
    "History of Georgia",
    "Ancient Georgia",
    "Kingdom of Colchis",
    "Kingdom of Iberia",
    "Lazica",
    "Tao-Klarjeti",
    "Dmanisi Hominin",
    "Archaeological Sites Georgia",
    "Vani",
    "Georgian Golden Age",
    "King David the Builder",
    "Queen Tamar",
    "Battle of Didgori",
    "Shota Rustaveli",
    "Mongol Invasion",
    "Ottoman Era",
    "Persian Era",
    "Russian Annexation",
    "Democratic Republic of Georgia (1918-1921)",
    "Soviet Georgia",
    "USSR",
    "9 April Tragedy",
    "Zviad Gamsakhurdia",
    "Eduard Shevardnadze",
    "Rose Revolution",
    "Modern Georgian History",
    "Bagrationi Dynasty",
    "Georgian Script",
    "Christianity in Georgia",
    "Saint Nino",
    "Uplistsikhe",
    "Vardzia",
    "David Gareja Lavra"
  ],
  culture: [
    "Georgian Culture",
    "Georgian Traditions",
    "Supra (Georgian Feast)",
    "Tamada (Toastmaster)",
    "Alaverti (Toast)",
    "Georgian Hospitality",
    "Georgian Dance",
    "Kartuli",
    "Khorumi",
    "Acharuli",
    "Georgian Polyphonic Singing",
    "Chakrulo",
    "UNESCO Intangible Cultural Heritage",
    "Georgian Festivals",
    "Tbilisoba",
    "Rtveli",
    "Alaverdoba",
    "Mariamoba",
    "Georgian Orthodox Church",
    "Religious Traditions",
    "Georgian Literature",
    "The Knight in the Panther's Skin",
    "Georgian Theatre",
    "Gabriadze Theater",
    "Georgian Cinema",
    "Modern Art Georgia",
    "Georgian Crafts",
    "Minankari (Cloisonné Enamel)",
    "Chokha (National Costume)",
    "Papakha",
    "Panduri",
    "Chiboni",
    "Georgian Customs",
    "Mekvle"
  ],
  nature: [
    "Nature of Georgia",
    "Wildlife of Georgia",
    "Endemic Species",
    "Caucasus Endemic Species",
    "National Parks of Georgia",
    "Protected Areas",
    "Kazbegi National Park",
    "Borjomi-Kharagauli National Park",
    "Vashlovani National Park",
    "Tusheti National Park",
    "Mtirala National Park",
    "Lagodekhi Protected Areas",
    "Algeti National Park",
    "Kintrishi Protected Area",
    "Georgian Flora and Fauna",
    "Caucasian Leopard",
    "Brown Bear",
    "Bezoar Goat",
    "Caucasian Tur",
    "Birdwatching Georgia",
    "Batumi Raptor Count",
    "Canyons of Georgia",
    "Martvili Canyon",
    "Okatse Canyon",
    "Dashbashi Canyon",
    "Caves in Georgia",
    "Prometheus Cave",
    "Sataplia Cave",
    "Lakes in Georgia",
    "Paravani Lake",
    "Ritsa Lake",
    "Black Sea Coast Georgia",
    "Subtropical Climate",
    "Alpine Zone",
    "Semi-desert",
    "Georgian Landscapes",
    "Waterfalls"
  ],
  adventure: [
    "Adventure in Georgia",
    "Adventure Travel",
    "Hiking in Georgia",
    "Trekking Caucasus",
    "Svaneti Trekking",
    "Mestia to Ushguli",
    "Tusheti Trekking",
    "Omalo",
    "Chaukhi Pass",
    "Lagodekhi Black Rock Lake",
    "Horse Riding Georgia",
    "Horse Riding Tusheti",
    "Paragliding Georgia",
    "Paragliding Gudauri",
    "Skiing in Georgia",
    "Gudauri Ski Resort",
    "Bakuriani Ski Resort",
    "Tetnuldi",
    "Hatsvali",
    "Rock Climbing Georgia",
    "Katskhi Pillar",
    "Chiatura",
    "Canyoning",
    "Rafting Georgia",
    "Rioni River Rafting",
    "Mtkvari River",
    "Caving",
    "Spelunking",
    "Ziplining",
    "Off-road Tours",
    "4x4 Georgia",
    "Jeep Tours",
    "Diving Black Sea",
    "Kvariati",
    "Camping Georgia"
  ],
  cuisine: [
    "Georgian Cuisine",
    "Traditional Georgian Food",
    "Khachapuri",
    "Imeretian Khachapuri",
    "Adjarian Khachapuri",
    "Megrelian Khachapuri",
    "Khinkali",
    "Mtsvadi (Shashlik)",
    "Satsivi",
    "Chkmeruli",
    "Chashushuli",
    "Ojakhuri",
    "Pkhali",
    "Badrijani Nigvzit (Eggplant with Walnuts)",
    "Lobio",
    "Ghomi",
    "Elarji",
    "Jonjoli",
    "Sulguni Cheese",
    "Imeretian Cheese",
    "Guda Cheese",
    "Svanetian Salt",
    "Ajika",
    "Tkemali Sauce",
    "Churchkhela",
    "Pelamushi",
    "Georgian Spices",
    "Georgian Bread (Shoti)",
    "Tone (Torn)",
    "Supra (Feast)",
    "Georgian Drinks",
    "Tarkhuna (Tarragon Lemonade)",
    "Borjomi Mineral Water",
    "Georgian Beer",
    "Chacha",
    "Cooking Classes Georgia",
    "Food Markets",
    "Tbilisi Food Scene"
  ],
  guide: [
    "Guided Tours Georgia",
    "Georgia Tour Packages",
    "Private Guides Georgia",
    "Driver-Guide Georgia",
    "Certified Guides",
    "Tbilisi City Tour",
    "Old Tbilisi Walking Tour",
    "Mtskheta Tour",
    "Kakheti Wine Tour",
    "Kazbegi Tour",
    "Gergeti Trinity Church",
    "Svaneti Tours",
    "Mestia",
    "Ushguli",
    "Kutaisi Tour",
    "Prometheus Cave Tour",
    "Martvili Canyon Tour",
    "Uplistsikhe Tour",
    "Vardzia Cave City Tour",
    "David Gareja Monastery Tour",
    "Tusheti Jeep Tour",
    "Cultural Tours",
    "Historical Tours",
    "Archaeological Tours",
    "Photography Tours",
    "Custom Tours Georgia",
    "Day Trips from Tbilisi"
  ],
  health: [
    "Health and Wellness Georgia",
    "Spa Resorts Georgia",
    "Balneotherapy Georgia",
    "Medical Tourism",
    "Sulphur Baths Tbilisi",
    "Abanotubani",
    "Borjomi Mineral Water",
    "Borjomi Health Resorts",
    "Tskaltubo",
    "Tskaltubo Spa Resorts",
    "Radon Baths",
    "Sairme",
    "Nunisi",
    "Shovi",
    "Therapeutic Mud",
    "Hydrotherapy",
    "Mineral Water Inhalation",
    "Wellness Retreats Georgia",
    "Yoga Retreats",
    "Relaxation",
    "Rejuvenation",
    "Nature Therapy",
    "Natural Hot Springs",
    "Natural Cold Springs",
    "Magnetic Sand Ureki",
    "Glamping Georgia",
    "Digital Detox"
  ],
  nightlife: [
    "Georgia Nightlife",
    "Tbilisi Nightlife",
    "Batumi Nightlife",
    "Kutaisi Nightlife",
    "Bars in Tbilisi",
    "Clubs in Tbilisi",
    "Techno Scene Georgia",
    "Bassiani",
    "Khidi",
    "Mtkvarze",
    "Cafe Gallery",
    "Fabrika Tbilisi",
    "Wine Bars Georgia",
    "Craft Beer Georgia",
    "Live Music Venues",
    "Rooftop Bars Tbilisi",
    "Shardeni Street",
    "Perovskaia Street",
    "New Tiflis",
    "Speakeasy Bars",
    "Batumi Boulevard",
    "Nightclubs in Batumi",
    "Beach Clubs Georgia"
  ],
  wine: [
    "Georgian Wine",
    "Cradle of Wine",
    "8000 Vintages",
    "Qvevri Wine",
    "Qvevri Making",
    "UNESCO",
    "Amber Wine",
    "Natural Wine Georgia",
    "Georgian Grape Varieties",
    "Saperavi",
    "Rkatsiteli",
    "Mtsvane Kakhuri",
    "Kisi",
    "Khikhvi",
    "Chinuri",
    "Tsolikouri",
    "Usakhelouri",
    "Ojaleshi",
    "Aleksandrouli",
    "Kakheti Wine Region",
    "Telavi",
    "Sighnaghi",
    "Imereti Wine Region",
    "Racha-Lechkhumi Wine Region",
    "Kartli Wine Region",
    "Georgian Wine Microzones",
    "Tsinandali",
    "Kindzmarauli",
    "Mukuzani",
    "Khvanchkara",
    "Wine Tasting Georgia",
    "Wine Tours Kakheti",
    "Marani (Wine Cellar)",
    "Rtveli (Grape Harvest)",
    "Georgian Winemaking",
    "Wine Culture",
    "Georgian Wine Association"
  ]
};
export default tags;